# Allows hiding any entries which don't have box art images defined
hide_entries_without_box_art = false
# Directory to find box art in if an absolute path is not given
box_art_dir = "/home/phantomwise/.config/rofi-games/box-art"

# Define a new custom entry
[[entries]]
title = "GDLauncher"
launch_command = "gdlauncher"
# Looks for the image in the defined `box_art_dir`
path_box_art = "gdlauncher.png"
path_game_dir = "/opt/GDLauncher"

# Change box art for a title
[[entries]]
title = "Cyberpunk 2077"
path_box_art = "/home/rolv/images/cyberpunk.png"

# Define box art for a title e.g. Minecraft instances
# Modded Minecraft instances are always prefixed with "Minecraft: "
[[entries]]
title = "Minecraft: Fabulously Optimized"
path_box_art = "fabulously_optimized.png"

# Hide/disable a title
[[entries]]
title = "THE FINALS"
hide = true


# Angband
[[entries]]
title = "Angband"
launch_command = "angband"
path_box_art = "./angband.jpg"
# path_game_dir = "/nix/store/onlyjohnnixosknowswhere/"

# Cataclysm DDA Tiles
[[entries]]
title = "Cataclysm DDA (Tiles)"
launch_command = "cataclysm-tiles"
path_box_art = "./Cataclysm-DDA.png"
# path_game_dir = "/nix/store/onlyjohnnixosknowswhere/"

# Freedroid RPG
[[entries]]
title = "Freedroid RPG"
launch_command = "freedroidRPG"
# path_box_art = "./angband.jpg"
# path_game_dir = "/nix/store/onlyjohnnixosknowswhere/"

# Narsil
[[entries]]
title = "Narsil"
launch_command = "narsil"
# path_box_art = "./angband.jpg"
# path_game_dir = "/nix/store/onlyjohnnixosknowswhere/"

# OpenRCT2 (Flatpak)
[[entries]]
title = "OpenRCT2 (Flatpak)"
launch_command = "flatpak run --branch=stable --arch=x86_64 --command=openrct2 --file-forwarding"
path_box_art = "./OpenRCT2.png"
path_game_dir = "/var/lib/flatpak/app/io.openrct2.OpenRCT2"

# TOME2
[[entries]]
title = "TOME2"
launch_command = "angband"
# path_box_art = "./angband.jpg"
# path_game_dir = "/nix/store/onlyjohnnixosknowswhere/"

# Unciv
[[entries]]
title = "Unciv"
launch_command = "unciv"
path_box_art = "./Unciv.png"
# path_game_dir = "/nix/store/onlyjohnnixosknowswhere/"
